# markdown adn highlighter
markdown:     kramdown
highlighter:  rouge

# permalinks
permalink:    pretty

# Server
#url:         noobscroll.js.org
# baseurl:      ./

# Custom variables
version:      v1.0.3
theoremjs:
    repo:     https://github.com/arguiot/TheoremJS
    docs:     https://theorem.js.org/docs
eyejs:
  repo:       https://github.com/arguiot/EyeJS
  docs:       https://github.com/arguiot/EyeJS/wiki
  stargazers: https://github.com/arguiot/EyeJS/stargazers
displayjs:
  repo:       https://github.com/arguiot/DisplayJS
  download:   https://unpkg.com/display.js
  docs:       https://github.com/arguiot/DisplayJS/wiki
  stargazers: https://github.com/arguiot/DisplayJS/stargazers
  cdn:        https://unpkg.com/display.js

author:
  github:     https://github.com/arguiot
  twitter:    https://twitter.com/arthur_guiot
  mail:       mailto:arguiot@gmail.com
  facebook:   https://www.facebook.com/profile.php?id=100012180104056
inspiration:
  github:     https://github.com/lucasgruwez

tweet:        https://twitter.com/intent/tweet?screen_name=arthur_guiot
about:        about
